from __future__ import unicode_literals

from django.db import models


class Property(models.Model):
    id = models.CharField(max_length=50, primary_key=True)
    acres = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    acres_range = models.CharField(max_length=50, blank=True, null=True)
    agent_name = models.CharField(max_length=255, blank=True, null=True)
    allow_avm = models.CharField(max_length=1, blank=True, null=True)
    allow_comments = models.CharField(max_length=1, blank=True, null=True)
    annual_tax = models.FloatField(blank=True, null=True)
    approximate_age = models.IntegerField(blank=True, null=True)
    area_int = models.IntegerField(blank=True, null=True)
    area_name = models.CharField(max_length=100, blank=True, null=True)
    building_name = models.CharField(max_length=100, blank=True, null=True)
    call_to_action_label = models.CharField(max_length=100, blank=True, null=True)
    call_to_action_label2 = models.CharField(max_length=100, blank=True, null=True)
    call_to_action_value = models.CharField(max_length=100, blank=True, null=True)
    call_to_action_value2 = models.CharField(max_length=100, blank=True, null=True)
    cancelleddate = models.DateTimeField(blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    close_date = models.DateTimeField(blank=True, null=True)
    co_listing_agent_id = models.CharField(max_length=50, blank=True, null=True)
    co_listing_agent_name = models.CharField(max_length=255, blank=True, null=True)
    co_listing_agent_phone = models.CharField(max_length=25, blank=True, null=True)
    co_listing_office_id = models.CharField(max_length=50, blank=True, null=True)
    co_listing_office_name = models.CharField(max_length=255, blank=True, null=True)
    co_listing_office_phone = models.CharField(max_length=25, blank=True, null=True)
    co_selling_agent_id = models.CharField(max_length=50, blank=True, null=True)
    co_selling_agent_name = models.CharField(max_length=255, blank=True, null=True)
    co_selling_office_id = models.CharField(max_length=50, blank=True, null=True)
    co_selling_office_name = models.CharField(max_length=255, blank=True, null=True)
    community = models.CharField(max_length=100, blank=True, null=True)
    complex_name = models.CharField(max_length=100, blank=True, null=True)
    contractdate = models.DateTimeField(blank=True, null=True)
    countrycode = models.CharField(max_length=2, blank=True, null=True)
    county = models.CharField(max_length=100, blank=True, null=True)
    custom1 = models.CharField(max_length=100, blank=True, null=True)
    custom2 = models.CharField(max_length=100, blank=True, null=True)
    custom3 = models.CharField(max_length=100, blank=True, null=True)
    custom4 = models.IntegerField(blank=True, null=True)
    custom5 = models.IntegerField(blank=True, null=True)
    custom6 = models.FloatField(blank=True, null=True)
    custom7 = models.CharField(max_length=1, blank=True, null=True)
    custom8 = models.CharField(max_length=1, blank=True, null=True)
    custom9 = models.CharField(max_length=1, blank=True, null=True)
    custom10 = models.CharField(max_length=1, blank=True, null=True)
    custom11 = models.CharField(max_length=1, blank=True, null=True)
    custom12 = models.CharField(max_length=1, blank=True, null=True)
    custom13 = models.CharField(max_length=1, blank=True, null=True)
    custom14 = models.CharField(max_length=1, blank=True, null=True)
    custom15 = models.CharField(max_length=100, blank=True, null=True)
    custom16 = models.CharField(max_length=500, blank=True, null=True)
    custom17 = models.CharField(max_length=500, blank=True, null=True)
    custom18 = models.CharField(max_length=500, blank=True, null=True)
    custom19 = models.CharField(max_length=500, blank=True, null=True)
    custom20 = models.CharField(max_length=500, blank=True, null=True)
    custom21 = models.CharField(max_length=500, blank=True, null=True)
    custom22 = models.CharField(max_length=500, blank=True, null=True)
    custom23 = models.CharField(max_length=500, blank=True, null=True)
    custom24 = models.CharField(max_length=500, blank=True, null=True)
    custom25 = models.CharField(max_length=500, blank=True, null=True)
    days_on_market = models.IntegerField(blank=True, null=True)
    display_address = models.CharField(max_length=255, blank=True, null=True)
    display_lat = models.FloatField(blank=True, null=True)
    display_lng = models.FloatField(blank=True, null=True)
    display_mlsnumber = models.CharField(max_length=15, blank=True, null=True)
    down_payment_resource = models.CharField(max_length=1, blank=True, null=True)
    elementary_school = models.CharField(max_length=100, blank=True, null=True)
    expirationdate = models.DateTimeField(blank=True, null=True)
    family_room = models.CharField(max_length=1, blank=True, null=True)
    fireplace = models.CharField(max_length=1, blank=True, null=True)
    foreclosure_type = models.CharField(max_length=50, blank=True, null=True)
    garage = models.CharField(max_length=500, blank=True, null=True)
    garage_spaces = models.IntegerField(blank=True, null=True)
    gated_community = models.CharField(max_length=1, blank=True, null=True)
    geocode_date = models.DateTimeField(blank=True, null=True)
    geocodequality = models.CharField(max_length=255, blank=True, null=True)
    golf_community = models.CharField(max_length=1, blank=True, null=True)
    has_basement = models.CharField(max_length=1, blank=True, null=True)
    has_garage = models.CharField(max_length=1, blank=True, null=True)
    has_golf = models.CharField(max_length=1, blank=True, null=True)
    has_horse_property = models.CharField(max_length=1, blank=True, null=True)
    has_lakefront = models.CharField(max_length=1, blank=True, null=True)
    has_mountain_view = models.CharField(max_length=1, blank=True, null=True)
    has_open_house = models.CharField(max_length=1, blank=True, null=True)
    has_pool = models.CharField(max_length=1, blank=True, null=True)
    has_waterfront = models.CharField(max_length=1, blank=True, null=True)
    has_waterview = models.CharField(max_length=1, blank=True, null=True)
    hash_value = models.CharField(max_length=32, blank=True, null=True)
    hide_address = models.CharField(max_length=1, blank=True, null=True)
    high_school = models.CharField(max_length=100, blank=True, null=True)
    idx = models.CharField(max_length=1, blank=True, null=True)
    is_adult_community = models.CharField(max_length=1, blank=True, null=True)
    is_boat_slip = models.CharField(max_length=1, blank=True, null=True)
    is_business_with_real_estate = models.CharField(max_length=1, blank=True, null=True)
    is_commercial = models.CharField(max_length=1, blank=True, null=True)
    is_commercial_lease = models.CharField(max_length=1, blank=True, null=True)
    is_condo = models.CharField(max_length=1, blank=True, null=True)
    is_condo_townhouse = models.CharField(max_length=1, blank=True, null=True)
    is_cul_de_sac = models.CharField(max_length=1, blank=True, null=True)
    is_custom1 = models.CharField(max_length=1, blank=True, null=True)
    is_custom2 = models.CharField(max_length=1, blank=True, null=True)
    is_custom3 = models.CharField(max_length=1, blank=True, null=True)
    is_custom4 = models.CharField(max_length=1, blank=True, null=True)
    is_custom5 = models.CharField(max_length=1, blank=True, null=True)
    is_duplex = models.CharField(max_length=1, blank=True, null=True)
    is_farm_hobby = models.CharField(max_length=1, blank=True, null=True)
    is_foreclosure = models.CharField(max_length=1, blank=True, null=True)
    is_half_duplex = models.CharField(max_length=1, blank=True, null=True)
    is_industrial = models.CharField(max_length=1, blank=True, null=True)
    is_investment = models.CharField(max_length=1, blank=True, null=True)
    is_loft = models.CharField(max_length=1, blank=True, null=True)
    is_lot = models.CharField(max_length=1, blank=True, null=True)
    is_mixed_use = models.CharField(max_length=1, blank=True, null=True)
    is_mobile_home = models.CharField(max_length=1, blank=True, null=True)
    is_model = models.CharField(max_length=1, blank=True, null=True)
    is_multi_family = models.CharField(max_length=1, blank=True, null=True)
    is_rental = models.CharField(max_length=1, blank=True, null=True)
    is_residential_lease = models.CharField(max_length=1, blank=True, null=True)
    is_residential_lease_detached = models.CharField(max_length=1, blank=True, null=True)
    is_retail_store = models.CharField(max_length=1, blank=True, null=True)
    is_shortsale = models.CharField(max_length=1, blank=True, null=True)
    is_single_family = models.CharField(max_length=1, blank=True, null=True)
    is_single_family_detached = models.CharField(max_length=1, blank=True, null=True)
    is_townhouse = models.CharField(max_length=1, blank=True, null=True)
    jr_high_school = models.CharField(max_length=100, blank=True, null=True)
    lake_name = models.CharField(max_length=100, blank=True, null=True)
    last_update_date = models.DateTimeField(blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    list_date = models.DateTimeField(blank=True, null=True)
    listing_agent_id = models.CharField(max_length=50, blank=True, null=True)
    listing_agent_phone = models.CharField(max_length=25, blank=True, null=True)
    listing_office_id = models.CharField(max_length=50, blank=True, null=True)
    listing_office_phone = models.CharField(max_length=25, blank=True, null=True)
    listing_price = models.TextField(blank=True, null=True)  # This field type is a guess.
    listing_status = models.CharField(max_length=100, blank=True, null=True)
    listing_status_standardized = models.CharField(max_length=50, blank=True, null=True)
    lng = models.FloatField(blank=True, null=True)
    lot_dimension = models.CharField(max_length=100, blank=True, null=True)
    market_name = models.CharField(max_length=20, blank=True, null=True)
    middle_school = models.CharField(max_length=100, blank=True, null=True)
    mls_create_date = models.DateTimeField(blank=True, null=True)
    mls_geocodequality = models.CharField(max_length=255, blank=True, null=True)
    mls_lat = models.FloatField(blank=True, null=True)
    mls_list_date = models.DateTimeField(blank=True, null=True)
    mls_lng = models.FloatField(blank=True, null=True)
    mls_update_date = models.DateTimeField(blank=True, null=True)
    neighborhood = models.CharField(max_length=100, blank=True, null=True)
    new_construction = models.CharField(max_length=1, blank=True, null=True)
    num_parking_spaces = models.IntegerField(blank=True, null=True)
    off_market_date = models.DateTimeField(blank=True, null=True)
    office_name = models.CharField(max_length=255, blank=True, null=True)
    on_golf_course = models.CharField(max_length=1, blank=True, null=True)
    one_story = models.CharField(max_length=1, blank=True, null=True)
    original_list_date = models.DateTimeField(blank=True, null=True)
    original_listing_price = models.TextField(blank=True, null=True)  # This field type is a guess.
    originatingsystemname = models.CharField(max_length=255, blank=True, null=True)
    pending_date = models.DateTimeField(blank=True, null=True)
    photo_url = models.CharField(max_length=255, blank=True, null=True)
    price_reduced = models.CharField(max_length=1, blank=True, null=True)
    property_sub_type = models.CharField(max_length=500, blank=True, null=True)
    property_type = models.CharField(max_length=500, blank=True, null=True)
    property_type_code = models.CharField(max_length=12, blank=True, null=True)
    property_type_standardized = models.CharField(max_length=50, blank=True, null=True)
    property_view = models.CharField(max_length=1, blank=True, null=True)
    school_district_id = models.IntegerField(blank=True, null=True)
    school_district_name = models.CharField(max_length=100, blank=True, null=True)
    selling_agent_id = models.CharField(max_length=50, blank=True, null=True)
    selling_agent_name = models.CharField(max_length=255, blank=True, null=True)
    selling_office_id = models.CharField(max_length=50, blank=True, null=True)
    selling_office_name = models.CharField(max_length=255, blank=True, null=True)
    selling_office_phone = models.CharField(max_length=25, blank=True, null=True)
    sold_date = models.DateTimeField(blank=True, null=True)
    sold_price = models.TextField(blank=True, null=True)  # This field type is a guess.
    square_feet = models.IntegerField(blank=True, null=True)
    square_feet_range = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=2, blank=True, null=True)
    state_prov_fullname = models.CharField(max_length=100, blank=True, null=True)
    status_change_date = models.DateTimeField(blank=True, null=True)
    street_direction = models.CharField(max_length=12, blank=True, null=True)
    street_name = models.CharField(max_length=120, blank=True, null=True)
    street_number = models.CharField(max_length=30, blank=True, null=True)
    street_type = models.CharField(max_length=120, blank=True, null=True)
    style = models.CharField(max_length=500, blank=True, null=True)
    subdivision = models.CharField(max_length=100, blank=True, null=True)
    temp_off_market_date = models.DateTimeField(blank=True, null=True)
    three_plus_story = models.CharField(max_length=1, blank=True, null=True)
    thumbnail_url = models.CharField(max_length=255, blank=True, null=True)
    total_bathrooms = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    total_bedrooms = models.IntegerField(blank=True, null=True)
    total_fireplaces = models.IntegerField(blank=True, null=True)
    total_full_baths = models.IntegerField(blank=True, null=True)
    total_half_baths = models.IntegerField(blank=True, null=True)
    total_partial_baths = models.IntegerField(blank=True, null=True)
    total_stories = models.IntegerField(blank=True, null=True)
    township = models.CharField(max_length=100, blank=True, null=True)
    two_story = models.CharField(max_length=1, blank=True, null=True)
    unit_number = models.CharField(max_length=20, blank=True, null=True)
    virtual_tour = models.CharField(max_length=255, blank=True, null=True)
    virtual_tour_branded = models.CharField(max_length=255, blank=True, null=True)
    waterfront = models.CharField(max_length=100, blank=True, null=True)
    wnt_create_date = models.DateTimeField(blank=True, null=True)
    year_built = models.IntegerField(blank=True, null=True)
    zip_code = models.CharField(max_length=11, blank=True, null=True)
    mls_id = models.CharField(max_length=255, blank=True, null=True)
    has_hoa = models.CharField(max_length=1, blank=True, null=True)
    listing_agent_email = models.CharField(max_length=255, blank=True, null=True)
    listing_office_name = models.CharField(max_length=255, blank=True, null=True)
    selling_agent_email = models.CharField(max_length=255, blank=True, null=True)
    selling_agent_phone = models.CharField(max_length=255, blank=True, null=True)
    co_listing_agent_email = models.CharField(max_length=255, blank=True, null=True)
    co_selling_agent_email = models.CharField(max_length=255, blank=True, null=True)
    is_coop = models.CharField(max_length=1, blank=True, null=True)
    is_other = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        db_table = 'properties'

    def __str__(self):
        return self.id


class PropertyAttribute(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    additional_features = models.CharField(max_length=500, blank=True, null=True)
    additional_remarks = models.CharField(max_length=2000, blank=True, null=True)
    additional_water_features = models.CharField(max_length=500, blank=True, null=True)
    air_conditioning = models.CharField(max_length=500, blank=True, null=True)
    annual_insurance = models.TextField(blank=True, null=True)  # This field type is a guess.
    annual_maintenance = models.TextField(blank=True, null=True)  # This field type is a guess.
    annual_management_fees = models.TextField(blank=True, null=True)  # This field type is a guess.
    annual_utilities = models.TextField(blank=True, null=True)  # This field type is a guess.
    appliances = models.CharField(max_length=500, blank=True, null=True)
    average_monthly_association_fee = models.TextField(blank=True, null=True)  # This field type is a guess.
    basement_description = models.CharField(max_length=500, blank=True, null=True)
    bathroom_1_description = models.CharField(max_length=500, blank=True, null=True)
    bathroom_1_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bathroom_1_length = models.IntegerField(blank=True, null=True)
    bathroom_1_level = models.CharField(max_length=1, blank=True, null=True)
    bathroom_1_width = models.IntegerField(blank=True, null=True)
    bathroom_2_description = models.CharField(max_length=500, blank=True, null=True)
    bathroom_2_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bathroom_2_length = models.IntegerField(blank=True, null=True)
    bathroom_2_level = models.CharField(max_length=1, blank=True, null=True)
    bathroom_2_width = models.IntegerField(blank=True, null=True)
    bathroom_3_description = models.CharField(max_length=500, blank=True, null=True)
    bathroom_3_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bathroom_3_length = models.IntegerField(blank=True, null=True)
    bathroom_3_level = models.CharField(max_length=1, blank=True, null=True)
    bathroom_3_width = models.IntegerField(blank=True, null=True)
    bedroom_1_description = models.CharField(max_length=500, blank=True, null=True)
    bedroom_1_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bedroom_1_length = models.IntegerField(blank=True, null=True)
    bedroom_1_level = models.CharField(max_length=1, blank=True, null=True)
    bedroom_1_width = models.IntegerField(blank=True, null=True)
    bedroom_2_description = models.CharField(max_length=500, blank=True, null=True)
    bedroom_2_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bedroom_2_length = models.IntegerField(blank=True, null=True)
    bedroom_2_level = models.CharField(max_length=1, blank=True, null=True)
    bedroom_2_width = models.IntegerField(blank=True, null=True)
    bedroom_3_description = models.CharField(max_length=500, blank=True, null=True)
    bedroom_3_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bedroom_3_length = models.IntegerField(blank=True, null=True)
    bedroom_3_level = models.CharField(max_length=1, blank=True, null=True)
    bedroom_3_width = models.IntegerField(blank=True, null=True)
    bedroom_4_description = models.CharField(max_length=500, blank=True, null=True)
    bedroom_4_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bedroom_4_length = models.IntegerField(blank=True, null=True)
    bedroom_4_level = models.CharField(max_length=1, blank=True, null=True)
    bedroom_4_width = models.IntegerField(blank=True, null=True)
    bedroom_5_description = models.CharField(max_length=500, blank=True, null=True)
    bedroom_5_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bedroom_5_length = models.IntegerField(blank=True, null=True)
    bedroom_5_level = models.CharField(max_length=1, blank=True, null=True)
    bedroom_5_width = models.IntegerField(blank=True, null=True)
    bedroom_6_description = models.CharField(max_length=500, blank=True, null=True)
    bedroom_6_dimensions = models.CharField(max_length=50, blank=True, null=True)
    bedroom_6_length = models.IntegerField(blank=True, null=True)
    bedroom_6_level = models.CharField(max_length=1, blank=True, null=True)
    bedroom_6_width = models.IntegerField(blank=True, null=True)
    below_grade = models.CharField(max_length=100, blank=True, null=True)
    body_of_water = models.CharField(max_length=100, blank=True, null=True)
    building_description = models.CharField(max_length=500, blank=True, null=True)
    ceiling_height = models.CharField(max_length=100, blank=True, null=True)
    contingencies = models.CharField(max_length=500, blank=True, null=True)
    current_use = models.CharField(max_length=100, blank=True, null=True)
    den_description = models.CharField(max_length=500, blank=True, null=True)
    den_dimensions = models.CharField(max_length=50, blank=True, null=True)
    den_length = models.IntegerField(blank=True, null=True)
    den_level = models.CharField(max_length=1, blank=True, null=True)
    den_width = models.IntegerField(blank=True, null=True)
    design = models.CharField(max_length=100, blank=True, null=True)
    dining_room_description = models.CharField(max_length=500, blank=True, null=True)
    dining_room_dimensions = models.CharField(max_length=50, blank=True, null=True)
    dining_room_length = models.IntegerField(blank=True, null=True)
    dining_room_level = models.CharField(max_length=1, blank=True, null=True)
    dining_room_width = models.IntegerField(blank=True, null=True)
    directions = models.CharField(max_length=500, blank=True, null=True)
    disability_features = models.CharField(max_length=500, blank=True, null=True)
    driveway = models.CharField(max_length=100, blank=True, null=True)
    easements = models.CharField(max_length=500, blank=True, null=True)
    exclusions = models.CharField(max_length=500, blank=True, null=True)
    exterior = models.CharField(max_length=500, blank=True, null=True)
    exterior_features = models.CharField(max_length=500, blank=True, null=True)
    extras = models.CharField(max_length=500, blank=True, null=True)
    family_room_description = models.CharField(max_length=500, blank=True, null=True)
    family_room_dimensions = models.CharField(max_length=50, blank=True, null=True)
    family_room_length = models.IntegerField(blank=True, null=True)
    family_room_level = models.CharField(max_length=1, blank=True, null=True)
    family_room_width = models.IntegerField(blank=True, null=True)
    fence_description = models.CharField(max_length=500, blank=True, null=True)
    financial_information = models.CharField(max_length=2000, blank=True, null=True)
    fireplace_description = models.CharField(max_length=500, blank=True, null=True)
    floor_information = models.CharField(max_length=500, blank=True, null=True)
    floor_load = models.IntegerField(blank=True, null=True)
    golf_description = models.CharField(max_length=500, blank=True, null=True)
    green_features = models.CharField(max_length=500, blank=True, null=True)
    gross_operating_income = models.TextField(blank=True, null=True)  # This field type is a guess.
    hash_value = models.CharField(max_length=32, blank=True, null=True)
    heat_source = models.CharField(max_length=500, blank=True, null=True)
    heat_type = models.CharField(max_length=500, blank=True, null=True)
    high_school = models.CharField(max_length=100, blank=True, null=True)
    hoa_amenities = models.CharField(max_length=500, blank=True, null=True)
    hoa_fee = models.TextField(blank=True, null=True)  # This field type is a guess.
    hoa_fee_includes = models.CharField(max_length=500, blank=True, null=True)
    hoa_frequency = models.CharField(max_length=100, blank=True, null=True)
    improvements = models.CharField(max_length=500, blank=True, null=True)
    interior_features = models.CharField(max_length=500, blank=True, null=True)
    interior_layout = models.CharField(max_length=500, blank=True, null=True)
    kitchen = models.CharField(max_length=500, blank=True, null=True)
    kitchen_description = models.CharField(max_length=500, blank=True, null=True)
    kitchen_dimensions = models.CharField(max_length=50, blank=True, null=True)
    kitchen_length = models.IntegerField(blank=True, null=True)
    kitchen_level = models.CharField(max_length=1, blank=True, null=True)
    kitchen_width = models.IntegerField(blank=True, null=True)
    lake_name = models.CharField(max_length=100, blank=True, null=True)
    landscape = models.CharField(max_length=500, blank=True, null=True)
    laundry_room_description = models.CharField(max_length=500, blank=True, null=True)
    laundry_room_dimensions = models.CharField(max_length=50, blank=True, null=True)
    laundry_room_length = models.IntegerField(blank=True, null=True)
    laundry_room_level = models.CharField(max_length=1, blank=True, null=True)
    laundry_room_width = models.IntegerField(blank=True, null=True)
    lease_information = models.CharField(max_length=100, blank=True, null=True)
    lease_only = models.CharField(max_length=1, blank=True, null=True)
    lease_price = models.TextField(blank=True, null=True)  # This field type is a guess.
    listing_agent_commission_rate = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    listing_agent_flat_fee = models.TextField(blank=True, null=True)  # This field type is a guess.
    living_room_description = models.CharField(max_length=500, blank=True, null=True)
    living_room_dimensions = models.CharField(max_length=50, blank=True, null=True)
    living_room_length = models.IntegerField(blank=True, null=True)
    living_room_level = models.CharField(max_length=1, blank=True, null=True)
    living_room_width = models.IntegerField(blank=True, null=True)
    lot_description = models.CharField(max_length=500, blank=True, null=True)
    lot_dimension = models.CharField(max_length=100, blank=True, null=True)
    master_bath_description = models.CharField(max_length=500, blank=True, null=True)
    master_bath_dimensions = models.CharField(max_length=50, blank=True, null=True)
    master_bath_length = models.IntegerField(blank=True, null=True)
    master_bath_level = models.CharField(max_length=1, blank=True, null=True)
    master_bath_width = models.IntegerField(blank=True, null=True)
    master_bedroom_description = models.CharField(max_length=500, blank=True, null=True)
    master_bedroom_dimensions = models.CharField(max_length=50, blank=True, null=True)
    master_bedroom_length = models.IntegerField(blank=True, null=True)
    master_bedroom_level = models.CharField(max_length=1, blank=True, null=True)
    master_bedroom_width = models.IntegerField(blank=True, null=True)
    middle_school = models.CharField(max_length=100, blank=True, null=True)
    new_construction = models.CharField(max_length=500, blank=True, null=True)
    outbuildings = models.CharField(max_length=500, blank=True, null=True)
    ownership = models.CharField(max_length=100, blank=True, null=True)
    parcel_number = models.CharField(max_length=50, blank=True, null=True)
    parking_description = models.CharField(max_length=500, blank=True, null=True)
    photo_count = models.IntegerField(blank=True, null=True)
    photo_date = models.DateTimeField(blank=True, null=True)
    photo_id = models.CharField(max_length=50, blank=True, null=True)
    pool = models.CharField(max_length=500, blank=True, null=True)
    pool_description = models.CharField(max_length=500, blank=True, null=True)
    property_view_description = models.CharField(max_length=500, blank=True, null=True)
    remarks = models.CharField(max_length=2000, blank=True, null=True)
    restrictions = models.CharField(max_length=500, blank=True, null=True)
    road_frontage = models.IntegerField(blank=True, null=True)
    road_frontage_description = models.CharField(max_length=500, blank=True, null=True)
    roofing = models.CharField(max_length=500, blank=True, null=True)
    rooms = models.CharField(max_length=500, blank=True, null=True)
    security_features = models.CharField(max_length=500, blank=True, null=True)
    seller_concessions = models.CharField(max_length=100, blank=True, null=True)
    selling_agent_commission_rate = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    selling_agent_flat_fee = models.CharField(max_length=50, blank=True, null=True)
    sewer = models.CharField(max_length=100, blank=True, null=True)
    square_feet_of_land = models.IntegerField(blank=True, null=True)
    square_foot_source = models.CharField(max_length=500, blank=True, null=True)
    stories_description = models.CharField(max_length=150, blank=True, null=True)
    style = models.CharField(max_length=500, blank=True, null=True)
    substructure = models.CharField(max_length=100, blank=True, null=True)
    tax_id = models.CharField(max_length=50, blank=True, null=True)
    tax_year = models.CharField(max_length=30, blank=True, null=True)
    tenant_pays = models.CharField(max_length=100, blank=True, null=True)
    topography = models.CharField(max_length=500, blank=True, null=True)
    total_expenses = models.TextField(blank=True, null=True)  # This field type is a guess.
    total_half_baths = models.IntegerField(blank=True, null=True)
    total_quarter_baths = models.IntegerField(blank=True, null=True)
    total_rooms = models.IntegerField(blank=True, null=True)
    total_three_quarter_baths = models.IntegerField(blank=True, null=True)
    total_units = models.IntegerField(blank=True, null=True)
    unit_1 = models.CharField(max_length=500, blank=True, null=True)
    unit_1_monthly_rent = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_1_rent_per_square_foot = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_1_square_footage = models.IntegerField(blank=True, null=True)
    unit_1_total_baths = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    unit_1_total_bedrooms = models.IntegerField(blank=True, null=True)
    unit_1_total_square_footage = models.IntegerField(blank=True, null=True)
    unit_1_total_units = models.IntegerField(blank=True, null=True)
    unit_2 = models.CharField(max_length=500, blank=True, null=True)
    unit_2_monthly_rent = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_2_rent_per_square_foot = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_2_square_footage = models.IntegerField(blank=True, null=True)
    unit_2_total_baths = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    unit_2_total_bedrooms = models.IntegerField(blank=True, null=True)
    unit_2_total_square_footage = models.IntegerField(blank=True, null=True)
    unit_2_total_units = models.IntegerField(blank=True, null=True)
    unit_3 = models.CharField(max_length=500, blank=True, null=True)
    unit_3_monthly_rent = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_3_rent_per_square_foot = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_3_square_footage = models.IntegerField(blank=True, null=True)
    unit_3_total_baths = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    unit_3_total_bedrooms = models.IntegerField(blank=True, null=True)
    unit_3_total_square_footage = models.IntegerField(blank=True, null=True)
    unit_3_total_units = models.IntegerField(blank=True, null=True)
    unit_4 = models.CharField(max_length=500, blank=True, null=True)
    unit_4_monthly_rent = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_4_rent_per_square_foot = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_4_square_footage = models.IntegerField(blank=True, null=True)
    unit_4_total_baths = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    unit_4_total_bedrooms = models.IntegerField(blank=True, null=True)
    unit_4_total_square_footage = models.IntegerField(blank=True, null=True)
    unit_4_total_units = models.IntegerField(blank=True, null=True)
    unit_5 = models.CharField(max_length=500, blank=True, null=True)
    unit_5_monthly_rent = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_5_rent_per_square_foot = models.TextField(blank=True, null=True)  # This field type is a guess.
    unit_5_square_footage = models.IntegerField(blank=True, null=True)
    unit_5_total_baths = models.DecimalField(max_digits=30, decimal_places=5, blank=True, null=True)
    unit_5_total_bedrooms = models.IntegerField(blank=True, null=True)
    unit_5_total_square_footage = models.IntegerField(blank=True, null=True)
    unit_5_total_units = models.IntegerField(blank=True, null=True)
    utilities = models.CharField(max_length=500, blank=True, null=True)
    utilities_available = models.CharField(max_length=500, blank=True, null=True)
    water = models.CharField(max_length=500, blank=True, null=True)
    water_features = models.CharField(max_length=500, blank=True, null=True)
    water_frontage = models.IntegerField(blank=True, null=True)
    waterfront_type = models.CharField(max_length=100, blank=True, null=True)
    windows = models.CharField(max_length=100, blank=True, null=True)
    zoning = models.CharField(max_length=100, blank=True, null=True)
    mls_id = models.CharField(max_length=255, blank=True, null=True)
    mls_update_date = models.DateTimeField(blank=True, null=True)
    cumulative_days_on_market = models.IntegerField(blank=True, null=True)
    occupant_type = models.CharField(max_length=100, blank=True, null=True)
    confidential_remarks = models.CharField(max_length=2000, blank=True, null=True)
    last_update_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'property_attributes'

    def __str__(self):
        return self.property


class Photo(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    photo_filename = models.CharField(max_length=128, blank=True, null=True)
    photo_url = models.CharField(max_length=255, blank=True, null=True)
    thumbnail_url = models.CharField(max_length=255, blank=True, null=True)
    caption = models.CharField(max_length=2000, blank=True, null=True)
    photo_date = models.DateTimeField(blank=True, null=True)
    display_order = models.IntegerField(blank=True, null=True)
    photo_category = models.CharField(max_length=20, blank=True, null=True)
    last_update_date = models.DateTimeField(blank=True, null=True)
    mls_update_date = models.DateTimeField(blank=True, null=True)
    mls_id = models.CharField(max_length=255, blank=True, null=True)
    hash_value = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        unique_together = ('property', 'display_order')
        db_table = 'photos'

    def __str__(self):
        return self.property


class MlsAgent(models.Model):
    ma_id = models.CharField(max_length=50, blank=True, null=True)
    ma_mo_id = models.CharField(max_length=50, blank=True, null=True)
    ma_nrds_id = models.CharField(max_length=50, blank=True, null=True)
    ma_full_name = models.CharField(max_length=255, blank=True, null=True)
    ma_first_name = models.CharField(max_length=50, blank=True, null=True)
    ma_middle_name = models.CharField(max_length=50, blank=True, null=True)
    ma_last_name = models.CharField(max_length=50, blank=True, null=True)
    ma_user_name = models.CharField(max_length=50, blank=True, null=True)
    ma_email = models.CharField(max_length=255, blank=True, null=True)
    ma_website = models.CharField(max_length=255, blank=True, null=True)
    ma_blog_address = models.CharField(max_length=255, blank=True, null=True)
    ma_preferred_language = models.CharField(max_length=50, blank=True, null=True)
    ma_preferred_phone = models.CharField(max_length=25, blank=True, null=True)
    ma_cell_phone = models.CharField(max_length=25, blank=True, null=True)
    ma_license_number = models.CharField(max_length=50, blank=True, null=True)
    ma_primary_association = models.CharField(max_length=255, blank=True, null=True)
    ma_designations = models.CharField(max_length=255, blank=True, null=True)
    ma_type = models.CharField(max_length=50, blank=True, null=True)
    ma_status = models.CharField(max_length=25, blank=True, null=True)
    ma_status_date = models.CharField(max_length=25, blank=True, null=True)
    ma_source_modification_timestamp = models.CharField(max_length=25, blank=True, null=True)
    ma_modification_timestamp = models.CharField(max_length=25, blank=True, null=True)
    ma_system_locale = models.CharField(max_length=50, blank=True, null=True)
    ma_sub_system_locale = models.CharField(max_length=50, blank=True, null=True)
    ma_key = models.CharField(max_length=50, blank=True, null=True)
    ma_mo_key = models.CharField(max_length=50, blank=True, null=True)
    ma_toll_free_phone = models.CharField(max_length=25, blank=True, null=True)
    ma_source_creation_timestamp = models.CharField(max_length=25, blank=True, null=True)
    ma_country_code = models.CharField(max_length=2, blank=True, null=True)
    ma_luxury_listings_flag = models.CharField(max_length=1, blank=True, null=True)
    ma_commercial_listings_flag = models.CharField(max_length=1, blank=True, null=True)
    ma_mobile_carrier = models.CharField(max_length=50, blank=True, null=True)
    ma_photo_url = models.CharField(max_length=255, blank=True, null=True)
    ma_facebook_url = models.CharField(max_length=255, blank=True, null=True)
    ma_biography = models.CharField(max_length=2000, blank=True, null=True)
    mls_create_date = models.DateTimeField(blank=True, null=True)
    mls_update_date = models.DateTimeField(blank=True, null=True)
    wnt_create_date = models.DateTimeField(blank=True, null=True)
    last_update_date = models.DateTimeField(blank=True, null=True)
    mls_id = models.CharField(max_length=255, blank=True, null=True)
    hash_value = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        unique_together = ('ma_id', 'ma_mo_id')
        db_table = 'mls_agents'


class MlsOffice(models.Model):
    mo_id = models.CharField(max_length=50, blank=True, null=True)
    mo_nrds_id = models.CharField(max_length=50, blank=True, null=True)
    mo_full_name = models.CharField(max_length=255, blank=True, null=True)
    mo_email = models.CharField(max_length=255, blank=True, null=True)
    mo_website = models.CharField(max_length=255, blank=True, null=True)
    mo_phone = models.CharField(max_length=25, blank=True, null=True)
    mo_address = models.CharField(max_length=255, blank=True, null=True)
    mo_city = models.CharField(max_length=100, blank=True, null=True)
    mo_state = models.CharField(max_length=2, blank=True, null=True)
    mo_zip_code = models.CharField(max_length=11, blank=True, null=True)
    mo_zip_code_4 = models.CharField(max_length=4, blank=True, null=True)
    mo_broker_id = models.CharField(max_length=50, blank=True, null=True)
    mo_primary_association = models.CharField(max_length=255, blank=True, null=True)
    mo_type = models.CharField(max_length=50, blank=True, null=True)
    mo_status = models.CharField(max_length=25, blank=True, null=True)
    mo_status_date = models.CharField(max_length=25, blank=True, null=True)
    mo_source_creation_timestamp = models.CharField(max_length=25, blank=True, null=True)
    mo_source_modification_timestamp = models.CharField(max_length=25, blank=True, null=True)
    mo_modification_timestamp = models.CharField(max_length=25, blank=True, null=True)
    mo_system_locale = models.CharField(max_length=50, blank=True, null=True)
    mo_sub_system_locale = models.CharField(max_length=50, blank=True, null=True)
    mo_key = models.CharField(max_length=50, blank=True, null=True)
    mo_short_name = models.CharField(max_length=100, blank=True, null=True)
    mo_contact_first_name = models.CharField(max_length=100, blank=True, null=True)
    mo_contact_last_name = models.CharField(max_length=100, blank=True, null=True)
    mo_contact_full_name = models.CharField(max_length=100, blank=True, null=True)
    mo_contact_email = models.CharField(max_length=100, blank=True, null=True)
    mo_contact_phone = models.CharField(max_length=100, blank=True, null=True)
    mo_broker_first_name = models.CharField(max_length=100, blank=True, null=True)
    mo_broker_last_name = models.CharField(max_length=100, blank=True, null=True)
    mo_broker_full_name = models.CharField(max_length=100, blank=True, null=True)
    mo_broker_email = models.CharField(max_length=100, blank=True, null=True)
    mo_broker_phone = models.CharField(max_length=100, blank=True, null=True)
    mo_country_code = models.CharField(max_length=2, blank=True, null=True)
    mo_parent_org_id = models.CharField(max_length=100, blank=True, null=True)
    mo_min_luxury_price = models.CharField(max_length=100, blank=True, null=True)
    mo_state_prov_service_area = models.CharField(max_length=100, blank=True, null=True)
    mo_broker_logo_text = models.CharField(max_length=100, blank=True, null=True)
    wnt_create_date = models.DateTimeField(blank=True, null=True)
    last_update_date = models.DateTimeField(blank=True, null=True)
    mls_id = models.CharField(max_length=255, blank=True, null=True)
    mls_update_date = models.DateTimeField(blank=True, null=True)
    mls_create_date = models.DateTimeField(blank=True, null=True)
    hash_value = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        db_table = 'mls_offices'


class OpenHouse(models.Model):
    agent_fullname = models.CharField(max_length=8000, blank=True, null=True)
    bathstotal = models.CharField(max_length=8000, blank=True, null=True)
    bedrooms = models.CharField(max_length=8000, blank=True, null=True)
    city = models.CharField(max_length=8000, blank=True, null=True)
    directions = models.CharField(max_length=8000, blank=True, null=True)
    district = models.CharField(max_length=8000, blank=True, null=True)
    foundationsize = models.CharField(max_length=8000, blank=True, null=True)
    fromdate = models.CharField(max_length=8000, blank=True, null=True)
    fromtime = models.CharField(max_length=8000, blank=True, null=True)
    inputdate = models.CharField(max_length=8000, blank=True, null=True)
    is_active = models.CharField(max_length=8000, blank=True, null=True)
    listagent1agentid = models.CharField(max_length=8000, blank=True, null=True)
    listofficeid = models.CharField(max_length=8000, blank=True, null=True)
    listprice = models.CharField(max_length=8000, blank=True, null=True)
    livingarea = models.CharField(max_length=8000, blank=True, null=True)
    mlnumber = models.CharField(max_length=8000, blank=True, null=True)
    modificationtimestamp = models.CharField(max_length=8000, blank=True, null=True)
    office_officename = models.CharField(max_length=8000, blank=True, null=True)
    postalcode = models.CharField(max_length=8000, blank=True, null=True)
    preferredphone = models.CharField(max_length=8000, blank=True, null=True)
    publicremarks = models.CharField(max_length=8000, blank=True, null=True)
    refreshments = models.CharField(max_length=8000, blank=True, null=True)
    remarks = models.CharField(max_length=8000, blank=True, null=True)
    schooldistrictnumber = models.CharField(max_length=8000, blank=True, null=True)
    stateorprovince = models.CharField(max_length=8000, blank=True, null=True)
    status = models.CharField(max_length=8000, blank=True, null=True)
    streetaddress = models.CharField(max_length=8000, blank=True, null=True)
    streetdirprefix = models.CharField(max_length=8000, blank=True, null=True)
    streetdirsuffix = models.CharField(max_length=8000, blank=True, null=True)
    streetname = models.CharField(max_length=8000, blank=True, null=True)
    streetnumber = models.CharField(max_length=8000, blank=True, null=True)
    streetnumbernumeric = models.CharField(max_length=8000, blank=True, null=True)
    streetsuffix = models.CharField(max_length=8000, blank=True, null=True)
    style = models.CharField(max_length=8000, blank=True, null=True)
    style_compact = models.CharField(max_length=8000, blank=True, null=True)
    tablename = models.CharField(max_length=8000, blank=True, null=True)
    tableuid = models.CharField(max_length=8000, blank=True, null=True)
    todate = models.CharField(max_length=8000, blank=True, null=True)
    totime = models.CharField(max_length=8000, blank=True, null=True)
    type = models.CharField(max_length=8000, blank=True, null=True)
    uid = models.CharField(max_length=8000, blank=True, null=True)
    unitnumber = models.CharField(max_length=8000, blank=True, null=True)
    wnt_create_date = models.DateTimeField(blank=True, null=True)
    last_update_date = models.DateTimeField(blank=True, null=True)
    mls_create_date = models.DateTimeField(blank=True, null=True)
    mls_update_date = models.DateTimeField(blank=True, null=True)
    mls_id = models.CharField(max_length=255, blank=True, null=True)
    properties_mls_id = models.CharField(max_length=255, blank=True, null=True)
    hash_value = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        db_table = 'open_house'


class PropertyRoom(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    room_label = models.CharField(max_length=255, blank=True, null=True)
    room_level = models.CharField(max_length=50, blank=True, null=True)
    room_dimensions = models.CharField(max_length=50, blank=True, null=True)
    room_length = models.IntegerField(blank=True, null=True)
    room_width = models.IntegerField(blank=True, null=True)
    room_description = models.CharField(max_length=500, blank=True, null=True)
    display_order = models.IntegerField(blank=True, null=True)
    wnt_create_date = models.DateTimeField(blank=True, null=True)
    last_update_date = models.DateTimeField(blank=True, null=True)
    mls_create_date = models.DateTimeField(blank=True, null=True)
    mls_update_date = models.DateTimeField(blank=True, null=True)
    mls_id = models.CharField(max_length=255, blank=True, null=True)
    properties_mls_id = models.CharField(max_length=255, blank=True, null=True)
    hash_value = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        db_table = 'property_rooms'

    def __str__(self):
        return self.title


class WntDataProvHistory(models.Model):
    db_source = models.CharField(max_length=255, blank=True, null=True)
    db_dest = models.CharField(max_length=255, blank=True, null=True)
    count_properties = models.IntegerField(blank=True, null=True)
    count_property_attributes = models.IntegerField(blank=True, null=True)
    count_property_market_fields = models.IntegerField(blank=True, null=True)
    count_photos = models.IntegerField(blank=True, null=True)
    count_mls_agents = models.IntegerField(blank=True, null=True)
    count_mls_offices = models.IntegerField(blank=True, null=True)
    count_open_house = models.IntegerField(blank=True, null=True)
    max_list_date = models.DateTimeField(blank=True, null=True)
    max_update_date = models.DateTimeField(blank=True, null=True)
    prov_start_time = models.DateTimeField(blank=True, null=True)
    prov_end_time = models.DateTimeField(blank=True, null=True)
    prov_success = models.CharField(max_length=1, blank=True, null=True)
    prov_notes = models.CharField(max_length=2000, blank=True, null=True)

    class Meta:
        db_table = 'wnt_data_prov_history'
